
export METISROOT=/home/cd/metis

export LD_LIBRARY_PATH=$METISROOT/lib:$LD_LIBRARY_PATH
export CPATH=$METISROOT/include:$CPATH

export TECIOROOT=/home/cd/TECIO

export LD_LIBRARY_PATH=$TECIOROOT/lib:$LD_LIBRARY_PATH
export CPATH=$TECIOROOT/include:$CPATH
